### PR TITLE
Format code

### PR DESCRIPTION
**Pull request by lvn-rusty-dragon**

### CODE REVIEW

**Comment by lvn-rusty-dragon** [comment]
@lvn-alduin this was my attempt to getting the codebase to pass linting/formatting with Biome, I wanted to avoid each PR I made causing a large code change. There are still a number of lints that are failing. Can you review? We can schedule in the work to fix those if necessary.

**Comment by lvn-alduin** [comment]
I'm looking now

**Comment by lvn-alduin** [comment]
Ok, there we go @lvn-rusty-dragon. Are we good to merge?

**Comment by lvn-rusty-dragon** [comment]
Yes, thanks! Please approve/merge when ready.

**Review by lvn-alduin — APPROVED** [review]

**Pull request merged**
